Repository googleapis/google-api-ruby-client, pull requests merged in 2019-05, with the labels that each got.

#783 Delete .env
  samples/web/.env
Labels: cla: yes

#785 Remove extra space in method template
  README.md
  lib/google/apis/generator/templates/_method.tmpl
Labels: cla: yes

#776 Deserialize type: Date values
  lib/google/apis/core/json_representation.rb
  spec/google/apis/core/json_representation_spec.rb
Labels: :rotating_light:, cla: yes

#787 Fix generate-api names_out usage
  bin/generate-api
Labels: cla: yes, type: bug

#789 Replace mime-types dependency with mini_mime
  google-api-client.gemspec
  lib/google/apis/core/upload.rb
Labels: cla: yes
