Repository googleapis/google-api-ruby-client, pull requests merged in 2021-12, with the labels that each got.

#7486 feat: Automated regeneration of adsense v2 client
  generated/google-apis-adsense_v2/CHANGELOG.md
  generated/google-apis-adsense_v2/lib/google/apis/adsense_v2/classes.rb
  generated/google-apis-adsense_v2/lib/google/apis/adsense_v2/gem_version.rb
  generated/google-apis-adsense_v2/lib/google/apis/adsense_v2/service.rb
  generated/google-apis-adsense_v2/synth.metadata
Labels: cla: yes, automerge

#7487 feat: Automated regeneration of chat v1 client
  generated/google-apis-chat_v1/CHANGELOG.md
  generated/google-apis-chat_v1/lib/google/apis/chat_v1/classes.rb
  generated/google-apis-chat_v1/lib/google/apis/chat_v1/gem_version.rb
  generated/google-apis-chat_v1/lib/google/apis/chat_v1/service.rb
  generated/google-apis-chat_v1/synth.metadata
Labels: cla: yes, automerge

#7488 feat: Automated regeneration of cloudsearch v1 client
  generated/google-apis-cloudsearch_v1/CHANGELOG.md
  generated/google-apis-cloudsearch_v1/lib/google/apis/cloudsearch_v1/gem_version.rb
  generated/google-apis-cloudsearch_v1/lib/google/apis/cloudsearch_v1/service.rb
  generated/google-apis-cloudsearch_v1/synth.metadata
Labels: cla: yes, automerge

#7489 feat: Automated regeneration of content v2.1 client
  generated/google-apis-content_v2_1/CHANGELOG.md
  generated/google-apis-content_v2_1/lib/google/apis/content_v2_1/classes.rb
  generated/google-apis-content_v2_1/lib/google/apis/content_v2_1/gem_version.rb
  generated/google-apis-content_v2_1/lib/google/apis/content_v2_1/service.rb
  generated/google-apis-content_v2_1/synth.metadata
Labels: cla: yes, automerge

#7490 feat: Automated regeneration of accessapproval v1 client
  generated/google-apis-accessapproval_v1/CHANGELOG.md
  generated/google-apis-accessapproval_v1/lib/google/apis/accessapproval_v1/classes.rb
  generated/google-apis-accessapproval_v1/lib/google/apis/accessapproval_v1/gem_version.rb
  generated/google-apis-accessapproval_v1/synth.metadata
Labels: cla: yes, automerge

#7492 feat: Automated regeneration of androidmanagement v1 client
  generated/google-apis-androidmanagement_v1/CHANGELOG.md
  generated/google-apis-androidmanagement_v1/lib/google/apis/androidmanagement_v1/classes.rb
  generated/google-apis-androidmanagement_v1/lib/google/apis/androidmanagement_v1/gem_version.rb
  generated/google-apis-androidmanagement_v1/synth.metadata
Labels: cla: yes, automerge

#7501 feat: Automated regeneration of dfareporting v3.4 client
  generated/google-apis-dfareporting_v3_4/CHANGELOG.md
  generated/google-apis-dfareporting_v3_4/lib/google/apis/dfareporting_v3_4/classes.rb
  generated/google-apis-dfareporting_v3_4/lib/google/apis/dfareporting_v3_4/gem_version.rb
  generated/google-apis-dfareporting_v3_4/synth.metadata
Labels: cla: yes, automerge

#7502 feat: Automated regeneration of dfareporting v3.5 client
  generated/google-apis-dfareporting_v3_5/CHANGELOG.md
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/classes.rb
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/gem_version.rb
  generated/google-apis-dfareporting_v3_5/synth.metadata
Labels: cla: yes, automerge

#7506 feat: Automated regeneration of storagetransfer v1 client
  generated/google-apis-storagetransfer_v1/CHANGELOG.md
  generated/google-apis-storagetransfer_v1/lib/google/apis/storagetransfer_v1/classes.rb
  generated/google-apis-storagetransfer_v1/lib/google/apis/storagetransfer_v1/gem_version.rb
  generated/google-apis-storagetransfer_v1/lib/google/apis/storagetransfer_v1/service.rb
  generated/google-apis-storagetransfer_v1/synth.metadata
Labels: cla: yes, automerge

#7507 feat: Automated regeneration of testing v1 client
  generated/google-apis-testing_v1/CHANGELOG.md
  generated/google-apis-testing_v1/lib/google/apis/testing_v1/classes.rb
  generated/google-apis-testing_v1/lib/google/apis/testing_v1/gem_version.rb
  generated/google-apis-testing_v1/synth.metadata
Labels: cla: yes, automerge

#7508 chore: Reenable releases
  .kokoro/release-generated.sh
Labels: cla: yes

#7512 feat: Automated regeneration of bigqueryconnection v1beta1 client
  generated/google-apis-bigqueryconnection_v1beta1/CHANGELOG.md
  generated/google-apis-bigqueryconnection_v1beta1/lib/google/apis/bigqueryconnection_v1beta1/classes.rb
  generated/google-apis-bigqueryconnection_v1beta1/lib/google/apis/bigqueryconnection_v1beta1/gem_version.rb
  generated/google-apis-bigqueryconnection_v1beta1/synth.metadata
Labels: cla: yes, automerge

#7513 feat: Automated regeneration of bigquerydatatransfer v1 client
  generated/google-apis-bigquerydatatransfer_v1/CHANGELOG.md
  generated/google-apis-bigquerydatatransfer_v1/lib/google/apis/bigquerydatatransfer_v1/classes.rb
  generated/google-apis-bigquerydatatransfer_v1/lib/google/apis/bigquerydatatransfer_v1/gem_version.rb
  generated/google-apis-bigquerydatatransfer_v1/synth.metadata
Labels: cla: yes, automerge

#7514 feat: Automated regeneration of dfareporting v3.5 client
  generated/google-apis-dfareporting_v3_5/CHANGELOG.md
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/classes.rb
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/gem_version.rb
  generated/google-apis-dfareporting_v3_5/synth.metadata
Labels: cla: yes, automerge

#7519 feat: Automated regeneration of monitoring v3 client
  generated/google-apis-monitoring_v3/CHANGELOG.md
  generated/google-apis-monitoring_v3/lib/google/apis/monitoring_v3/classes.rb
  generated/google-apis-monitoring_v3/lib/google/apis/monitoring_v3/gem_version.rb
  generated/google-apis-monitoring_v3/synth.metadata
Labels: cla: yes, automerge

#7520 feat: Automated regeneration of dfareporting v3.5 client
  generated/google-apis-dfareporting_v3_5/CHANGELOG.md
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/classes.rb
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/gem_version.rb
  generated/google-apis-dfareporting_v3_5/synth.metadata
Labels: cla: yes, automerge

#7521 feat: Automated regeneration of spanner v1 client
  generated/google-apis-spanner_v1/CHANGELOG.md
  generated/google-apis-spanner_v1/lib/google/apis/spanner_v1/classes.rb
  generated/google-apis-spanner_v1/lib/google/apis/spanner_v1/gem_version.rb
  generated/google-apis-spanner_v1/synth.metadata
Labels: cla: yes, automerge

#7522 feat: Automated regeneration of storage v1 client
  generated/google-apis-storage_v1/CHANGELOG.md
  generated/google-apis-storage_v1/lib/google/apis/storage_v1/classes.rb
  generated/google-apis-storage_v1/lib/google/apis/storage_v1/gem_version.rb
  generated/google-apis-storage_v1/synth.metadata
Labels: cla: yes, automerge

#7524 feat: Automated regeneration of vmmigration v1alpha1 client
  generated/google-apis-vmmigration_v1alpha1/CHANGELOG.md
  generated/google-apis-vmmigration_v1alpha1/lib/google/apis/vmmigration_v1alpha1/classes.rb
  generated/google-apis-vmmigration_v1alpha1/lib/google/apis/vmmigration_v1alpha1/gem_version.rb
  generated/google-apis-vmmigration_v1alpha1/synth.metadata
Labels: cla: yes, automerge

#7527 feat: Automated regeneration of cloudfunctions v1 client
  generated/google-apis-cloudfunctions_v1/CHANGELOG.md
  generated/google-apis-cloudfunctions_v1/lib/google/apis/cloudfunctions_v1/gem_version.rb
  generated/google-apis-cloudfunctions_v1/lib/google/apis/cloudfunctions_v1/service.rb
  generated/google-apis-cloudfunctions_v1/synth.metadata
Labels: automerge

#7535 feat: Automated regeneration of storagetransfer v1 client
  generated/google-apis-storagetransfer_v1/CHANGELOG.md
  generated/google-apis-storagetransfer_v1/lib/google/apis/storagetransfer_v1/classes.rb
  generated/google-apis-storagetransfer_v1/lib/google/apis/storagetransfer_v1/gem_version.rb
  generated/google-apis-storagetransfer_v1/synth.metadata
Labels: automerge

#7536 feat: Automated regeneration of texttospeech v1 client
  generated/google-apis-texttospeech_v1/CHANGELOG.md
  generated/google-apis-texttospeech_v1/lib/google/apis/texttospeech_v1/gem_version.rb
  generated/google-apis-texttospeech_v1/lib/google/apis/texttospeech_v1/service.rb
  generated/google-apis-texttospeech_v1/synth.metadata
Labels: automerge

#7537 feat: Automated regeneration of texttospeech v1beta1 client
  generated/google-apis-texttospeech_v1beta1/CHANGELOG.md
  generated/google-apis-texttospeech_v1beta1/lib/google/apis/texttospeech_v1beta1/gem_version.rb
  generated/google-apis-texttospeech_v1beta1/lib/google/apis/texttospeech_v1beta1/service.rb
  generated/google-apis-texttospeech_v1beta1/synth.metadata
Labels: automerge

#7542 feat: Automated regeneration of admin reports_v1 client
  generated/google-apis-admin_reports_v1/CHANGELOG.md
  generated/google-apis-admin_reports_v1/lib/google/apis/admin_reports_v1/gem_version.rb
  generated/google-apis-admin_reports_v1/lib/google/apis/admin_reports_v1/service.rb
  generated/google-apis-admin_reports_v1/synth.metadata
Labels: automerge

#7544 feat: Automated regeneration of artifactregistry v1beta1 client
  generated/google-apis-artifactregistry_v1beta1/CHANGELOG.md
  generated/google-apis-artifactregistry_v1beta1/lib/google/apis/artifactregistry_v1beta1/gem_version.rb
  generated/google-apis-artifactregistry_v1beta1/lib/google/apis/artifactregistry_v1beta1/service.rb
  generated/google-apis-artifactregistry_v1beta1/synth.metadata
Labels: automerge

#7549 feat: Automated regeneration of datacatalog v1beta1 client
  generated/google-apis-datacatalog_v1beta1/CHANGELOG.md
  generated/google-apis-datacatalog_v1beta1/lib/google/apis/datacatalog_v1beta1/classes.rb
  generated/google-apis-datacatalog_v1beta1/lib/google/apis/datacatalog_v1beta1/gem_version.rb
  generated/google-apis-datacatalog_v1beta1/lib/google/apis/datacatalog_v1beta1/service.rb
  generated/google-apis-datacatalog_v1beta1/synth.metadata
Labels: automerge

#7551 feat: Automated regeneration of cloudtasks v2 client
  generated/google-apis-cloudtasks_v2/CHANGELOG.md
  generated/google-apis-cloudtasks_v2/lib/google/apis/cloudtasks_v2/classes.rb
  generated/google-apis-cloudtasks_v2/lib/google/apis/cloudtasks_v2/gem_version.rb
  generated/google-apis-cloudtasks_v2/synth.metadata
Labels: automerge

#7552 feat: Automated regeneration of cloudtasks v2beta2 client
  generated/google-apis-cloudtasks_v2beta2/CHANGELOG.md
  generated/google-apis-cloudtasks_v2beta2/lib/google/apis/cloudtasks_v2beta2/classes.rb
  generated/google-apis-cloudtasks_v2beta2/lib/google/apis/cloudtasks_v2beta2/gem_version.rb
  generated/google-apis-cloudtasks_v2beta2/synth.metadata
Labels: automerge

#7553 feat: Automated regeneration of cloudtasks v2beta3 client
  generated/google-apis-cloudtasks_v2beta3/CHANGELOG.md
  generated/google-apis-cloudtasks_v2beta3/lib/google/apis/cloudtasks_v2beta3/classes.rb
  generated/google-apis-cloudtasks_v2beta3/lib/google/apis/cloudtasks_v2beta3/gem_version.rb
  generated/google-apis-cloudtasks_v2beta3/synth.metadata
Labels: automerge

#7555 feat: Automated regeneration of drive v2 client
  generated/google-apis-drive_v2/CHANGELOG.md
  generated/google-apis-drive_v2/lib/google/apis/drive_v2/gem_version.rb
  generated/google-apis-drive_v2/lib/google/apis/drive_v2/service.rb
  generated/google-apis-drive_v2/synth.metadata
Labels: automerge

#7562 feat: Automated regeneration of recommendationengine v1beta1 client
  generated/google-apis-recommendationengine_v1beta1/CHANGELOG.md
  generated/google-apis-recommendationengine_v1beta1/lib/google/apis/recommendationengine_v1beta1/gem_version.rb
  generated/google-apis-recommendationengine_v1beta1/lib/google/apis/recommendationengine_v1beta1/service.rb
  generated/google-apis-recommendationengine_v1beta1/synth.metadata
Labels: automerge

#7563 feat: Automated regeneration of recommender v1beta1 client
  generated/google-apis-recommender_v1beta1/CHANGELOG.md
  generated/google-apis-recommender_v1beta1/lib/google/apis/recommender_v1beta1/gem_version.rb
  generated/google-apis-recommender_v1beta1/lib/google/apis/recommender_v1beta1/service.rb
  generated/google-apis-recommender_v1beta1/synth.metadata
Labels: automerge

#7576 feat: Automated regeneration of dialogflow v2beta1 client
  generated/google-apis-dialogflow_v2beta1/CHANGELOG.md
  generated/google-apis-dialogflow_v2beta1/lib/google/apis/dialogflow_v2beta1/classes.rb
  generated/google-apis-dialogflow_v2beta1/lib/google/apis/dialogflow_v2beta1/gem_version.rb
  generated/google-apis-dialogflow_v2beta1/synth.metadata
Labels: automerge

#7575 feat: Automated regeneration of dialogflow v2 client
  generated/google-apis-dialogflow_v2/CHANGELOG.md
  generated/google-apis-dialogflow_v2/lib/google/apis/dialogflow_v2/classes.rb
  generated/google-apis-dialogflow_v2/lib/google/apis/dialogflow_v2/gem_version.rb
  generated/google-apis-dialogflow_v2/synth.metadata
Labels: automerge

#7579 feat: Automated regeneration of speech v1p1beta1 client
  generated/google-apis-speech_v1p1beta1/CHANGELOG.md
  generated/google-apis-speech_v1p1beta1/lib/google/apis/speech_v1p1beta1/classes.rb
  generated/google-apis-speech_v1p1beta1/lib/google/apis/speech_v1p1beta1/gem_version.rb
  generated/google-apis-speech_v1p1beta1/lib/google/apis/speech_v1p1beta1/service.rb
  generated/google-apis-speech_v1p1beta1/synth.metadata
Labels: automerge

#7578 feat: Automated regeneration of speech v1 client
  generated/google-apis-speech_v1/CHANGELOG.md
  generated/google-apis-speech_v1/lib/google/apis/speech_v1/classes.rb
  generated/google-apis-speech_v1/lib/google/apis/speech_v1/gem_version.rb
  generated/google-apis-speech_v1/lib/google/apis/speech_v1/service.rb
  generated/google-apis-speech_v1/synth.metadata
Labels: automerge

#7583 feat: Automated regeneration of datamigration v1beta1 client
  generated/google-apis-datamigration_v1beta1/CHANGELOG.md
  generated/google-apis-datamigration_v1beta1/lib/google/apis/datamigration_v1beta1/gem_version.rb
  generated/google-apis-datamigration_v1beta1/lib/google/apis/datamigration_v1beta1/service.rb
  generated/google-apis-datamigration_v1beta1/synth.metadata
Labels: automerge

#7584 feat: Automated regeneration of iamcredentials v1 client
  generated/google-apis-iamcredentials_v1/CHANGELOG.md
  generated/google-apis-iamcredentials_v1/lib/google/apis/iamcredentials_v1/classes.rb
  generated/google-apis-iamcredentials_v1/lib/google/apis/iamcredentials_v1/gem_version.rb
  generated/google-apis-iamcredentials_v1/synth.metadata
Labels: automerge

#7585 feat: Automated regeneration of logging v2 client
  generated/google-apis-logging_v2/CHANGELOG.md
  generated/google-apis-logging_v2/lib/google/apis/logging_v2/classes.rb
  generated/google-apis-logging_v2/lib/google/apis/logging_v2/gem_version.rb
  generated/google-apis-logging_v2/lib/google/apis/logging_v2/service.rb
  generated/google-apis-logging_v2/synth.metadata
Labels: automerge

#7602 feat: Automated regeneration of accessapproval v1 client
  generated/google-apis-accessapproval_v1/CHANGELOG.md
  generated/google-apis-accessapproval_v1/OVERVIEW.md
  generated/google-apis-accessapproval_v1/lib/google/apis/accessapproval_v1/gem_version.rb
  generated/google-apis-accessapproval_v1/synth.metadata
Labels: automerge

#7604 feat: Automated regeneration of accesscontextmanager v1beta client
  generated/google-apis-accesscontextmanager_v1beta/CHANGELOG.md
  generated/google-apis-accesscontextmanager_v1beta/OVERVIEW.md
  generated/google-apis-accesscontextmanager_v1beta/lib/google/apis/accesscontextmanager_v1beta/gem_version.rb
  generated/google-apis-accesscontextmanager_v1beta/synth.metadata
Labels: automerge

#7605 feat: Automated regeneration of adexchangebuyer2 v2beta1 client
  generated/google-apis-adexchangebuyer2_v2beta1/CHANGELOG.md
  generated/google-apis-adexchangebuyer2_v2beta1/OVERVIEW.md
  generated/google-apis-adexchangebuyer2_v2beta1/lib/google/apis/adexchangebuyer2_v2beta1/gem_version.rb
  generated/google-apis-adexchangebuyer2_v2beta1/synth.metadata
Labels: automerge

#7600 feat: Automated regeneration of abusiveexperiencereport v1 client
  generated/google-apis-abusiveexperiencereport_v1/CHANGELOG.md
  generated/google-apis-abusiveexperiencereport_v1/OVERVIEW.md
  generated/google-apis-abusiveexperiencereport_v1/lib/google/apis/abusiveexperiencereport_v1/gem_version.rb
  generated/google-apis-abusiveexperiencereport_v1/synth.metadata
Labels: automerge

#7607 feat: Automated regeneration of admin datatransfer_v1 client
  generated/google-apis-admin_datatransfer_v1/CHANGELOG.md
  generated/google-apis-admin_datatransfer_v1/OVERVIEW.md
  generated/google-apis-admin_datatransfer_v1/lib/google/apis/admin_datatransfer_v1/gem_version.rb
  generated/google-apis-admin_datatransfer_v1/synth.metadata
Labels: automerge

#7608 feat: Automated regeneration of admin directory_v1 client
  generated/google-apis-admin_directory_v1/CHANGELOG.md
  generated/google-apis-admin_directory_v1/OVERVIEW.md
  generated/google-apis-admin_directory_v1/lib/google/apis/admin_directory_v1/gem_version.rb
  generated/google-apis-admin_directory_v1/synth.metadata
Labels: automerge

#7612 feat: Automated regeneration of adsense v2 client
  generated/google-apis-adsense_v2/CHANGELOG.md
  generated/google-apis-adsense_v2/OVERVIEW.md
  generated/google-apis-adsense_v2/lib/google/apis/adsense_v2/gem_version.rb
  generated/google-apis-adsense_v2/synth.metadata
Labels: automerge

#7609 feat: Automated regeneration of admin reports_v1 client
  generated/google-apis-admin_reports_v1/CHANGELOG.md
  generated/google-apis-admin_reports_v1/OVERVIEW.md
  generated/google-apis-admin_reports_v1/lib/google/apis/admin_reports_v1/gem_version.rb
  generated/google-apis-admin_reports_v1/synth.metadata
Labels: automerge

#7613 feat: Automated regeneration of adsensehost v4.1 client
  generated/google-apis-adsensehost_v4_1/CHANGELOG.md
  generated/google-apis-adsensehost_v4_1/OVERVIEW.md
  generated/google-apis-adsensehost_v4_1/lib/google/apis/adsensehost_v4_1/gem_version.rb
  generated/google-apis-adsensehost_v4_1/synth.metadata
Labels: automerge

#7615 feat: Automated regeneration of analytics v3 client
  generated/google-apis-analytics_v3/CHANGELOG.md
  generated/google-apis-analytics_v3/OVERVIEW.md
  generated/google-apis-analytics_v3/lib/google/apis/analytics_v3/gem_version.rb
  generated/google-apis-analytics_v3/synth.metadata
Labels: automerge

#7606 feat: Automated regeneration of adexperiencereport v1 client
  generated/google-apis-adexperiencereport_v1/CHANGELOG.md
  generated/google-apis-adexperiencereport_v1/OVERVIEW.md
  generated/google-apis-adexperiencereport_v1/lib/google/apis/adexperiencereport_v1/gem_version.rb
  generated/google-apis-adexperiencereport_v1/synth.metadata
Labels: automerge

#7614 feat: Automated regeneration of alertcenter v1beta1 client
  generated/google-apis-alertcenter_v1beta1/CHANGELOG.md
  generated/google-apis-alertcenter_v1beta1/OVERVIEW.md
  generated/google-apis-alertcenter_v1beta1/lib/google/apis/alertcenter_v1beta1/gem_version.rb
  generated/google-apis-alertcenter_v1beta1/synth.metadata
Labels: automerge

#7619 feat: Automated regeneration of androiddeviceprovisioning v1 client
  generated/google-apis-androiddeviceprovisioning_v1/CHANGELOG.md
  generated/google-apis-androiddeviceprovisioning_v1/OVERVIEW.md
  generated/google-apis-androiddeviceprovisioning_v1/lib/google/apis/androiddeviceprovisioning_v1/gem_version.rb
  generated/google-apis-androiddeviceprovisioning_v1/synth.metadata
Labels: automerge

#7603 feat: Automated regeneration of accesscontextmanager v1 client
  generated/google-apis-accesscontextmanager_v1/CHANGELOG.md
  generated/google-apis-accesscontextmanager_v1/OVERVIEW.md
  generated/google-apis-accesscontextmanager_v1/lib/google/apis/accesscontextmanager_v1/gem_version.rb
  generated/google-apis-accesscontextmanager_v1/synth.metadata
Labels: automerge

#7617 feat: Automated regeneration of analyticsdata v1beta client
  generated/google-apis-analyticsdata_v1beta/CHANGELOG.md
  generated/google-apis-analyticsdata_v1beta/OVERVIEW.md
  generated/google-apis-analyticsdata_v1beta/lib/google/apis/analyticsdata_v1beta/classes.rb
  generated/google-apis-analyticsdata_v1beta/lib/google/apis/analyticsdata_v1beta/gem_version.rb
  generated/google-apis-analyticsdata_v1beta/lib/google/apis/analyticsdata_v1beta/representations.rb
  generated/google-apis-analyticsdata_v1beta/synth.metadata
Labels: automerge

#7618 feat: Automated regeneration of analyticsreporting v4 client
  generated/google-apis-analyticsreporting_v4/CHANGELOG.md
  generated/google-apis-analyticsreporting_v4/OVERVIEW.md
  generated/google-apis-analyticsreporting_v4/lib/google/apis/analyticsreporting_v4/gem_version.rb
  generated/google-apis-analyticsreporting_v4/synth.metadata
Labels: automerge

#7621 feat: Automated regeneration of androidmanagement v1 client
  generated/google-apis-androidmanagement_v1/CHANGELOG.md
  generated/google-apis-androidmanagement_v1/OVERVIEW.md
  generated/google-apis-androidmanagement_v1/lib/google/apis/androidmanagement_v1/gem_version.rb
  generated/google-apis-androidmanagement_v1/synth.metadata
Labels: automerge

#7601 feat: Automated regeneration of acceleratedmobilepageurl v1 client
  generated/google-apis-acceleratedmobilepageurl_v1/CHANGELOG.md
  generated/google-apis-acceleratedmobilepageurl_v1/OVERVIEW.md
  generated/google-apis-acceleratedmobilepageurl_v1/lib/google/apis/acceleratedmobilepageurl_v1/gem_version.rb
  generated/google-apis-acceleratedmobilepageurl_v1/synth.metadata
Labels: automerge

#7622 feat: Automated regeneration of androidpublisher v3 client
  generated/google-apis-androidpublisher_v3/CHANGELOG.md
  generated/google-apis-androidpublisher_v3/OVERVIEW.md
  generated/google-apis-androidpublisher_v3/lib/google/apis/androidpublisher_v3/gem_version.rb
  generated/google-apis-androidpublisher_v3/synth.metadata
Labels: automerge

#7620 feat: Automated regeneration of androidenterprise v1 client
  generated/google-apis-androidenterprise_v1/CHANGELOG.md
  generated/google-apis-androidenterprise_v1/OVERVIEW.md
  generated/google-apis-androidenterprise_v1/lib/google/apis/androidenterprise_v1/gem_version.rb
  generated/google-apis-androidenterprise_v1/synth.metadata
Labels: automerge

#7624 feat: Automated regeneration of apigateway v1beta client
  generated/google-apis-apigateway_v1beta/CHANGELOG.md
  generated/google-apis-apigateway_v1beta/OVERVIEW.md
  generated/google-apis-apigateway_v1beta/lib/google/apis/apigateway_v1beta/gem_version.rb
  generated/google-apis-apigateway_v1beta/synth.metadata
Labels: automerge

#7610 feat: Automated regeneration of admob v1 client
  generated/google-apis-admob_v1/CHANGELOG.md
  generated/google-apis-admob_v1/OVERVIEW.md
  generated/google-apis-admob_v1/lib/google/apis/admob_v1/gem_version.rb
  generated/google-apis-admob_v1/synth.metadata
Labels: automerge

#7626 feat: Automated regeneration of apikeys v2 client
  generated/google-apis-apikeys_v2/CHANGELOG.md
  generated/google-apis-apikeys_v2/OVERVIEW.md
  generated/google-apis-apikeys_v2/lib/google/apis/apikeys_v2/gem_version.rb
  generated/google-apis-apikeys_v2/synth.metadata
Labels: automerge

#7631 feat: Automated regeneration of artifactregistry v1 client
  generated/google-apis-artifactregistry_v1/CHANGELOG.md
  generated/google-apis-artifactregistry_v1/OVERVIEW.md
  generated/google-apis-artifactregistry_v1/lib/google/apis/artifactregistry_v1/gem_version.rb
  generated/google-apis-artifactregistry_v1/synth.metadata
Labels: automerge

#7627 feat: Automated regeneration of appengine v1 client
  generated/google-apis-appengine_v1/CHANGELOG.md
  generated/google-apis-appengine_v1/OVERVIEW.md
  generated/google-apis-appengine_v1/lib/google/apis/appengine_v1/gem_version.rb
  generated/google-apis-appengine_v1/synth.metadata
Labels: automerge

#7633 feat: Automated regeneration of artifactregistry v1beta2 client
  generated/google-apis-artifactregistry_v1beta2/CHANGELOG.md
  generated/google-apis-artifactregistry_v1beta2/OVERVIEW.md
  generated/google-apis-artifactregistry_v1beta2/lib/google/apis/artifactregistry_v1beta2/gem_version.rb
  generated/google-apis-artifactregistry_v1beta2/synth.metadata
Labels: automerge

#7634 feat: Automated regeneration of assuredworkloads v1 client
  generated/google-apis-assuredworkloads_v1/CHANGELOG.md
  generated/google-apis-assuredworkloads_v1/OVERVIEW.md
  generated/google-apis-assuredworkloads_v1/lib/google/apis/assuredworkloads_v1/gem_version.rb
  generated/google-apis-assuredworkloads_v1/synth.metadata
Labels: automerge

#7629 feat: Automated regeneration of appengine v1beta client
  generated/google-apis-appengine_v1beta/CHANGELOG.md
  generated/google-apis-appengine_v1beta/OVERVIEW.md
  generated/google-apis-appengine_v1beta/lib/google/apis/appengine_v1beta/gem_version.rb
  generated/google-apis-appengine_v1beta/synth.metadata
Labels: automerge

#7630 feat: Automated regeneration of area120tables v1alpha1 client
  generated/google-apis-area120tables_v1alpha1/CHANGELOG.md
  generated/google-apis-area120tables_v1alpha1/OVERVIEW.md
  generated/google-apis-area120tables_v1alpha1/lib/google/apis/area120tables_v1alpha1/gem_version.rb
  generated/google-apis-area120tables_v1alpha1/synth.metadata
Labels: automerge

#7623 feat: Automated regeneration of apigateway v1 client
  generated/google-apis-apigateway_v1/CHANGELOG.md
  generated/google-apis-apigateway_v1/OVERVIEW.md
  generated/google-apis-apigateway_v1/lib/google/apis/apigateway_v1/gem_version.rb
  generated/google-apis-apigateway_v1/synth.metadata
Labels: automerge

#7636 feat: Automated regeneration of baremetalsolution v1 client
  generated/google-apis-baremetalsolution_v1/CHANGELOG.md
  generated/google-apis-baremetalsolution_v1/OVERVIEW.md
  generated/google-apis-baremetalsolution_v1/lib/google/apis/baremetalsolution_v1/gem_version.rb
  generated/google-apis-baremetalsolution_v1/synth.metadata
Labels: automerge

#7642 feat: Automated regeneration of bigtableadmin v1 client
  generated/google-apis-bigtableadmin_v1/CHANGELOG.md
  generated/google-apis-bigtableadmin_v1/OVERVIEW.md
  generated/google-apis-bigtableadmin_v1/synth.metadata
Labels: automerge

#7643 feat: Automated regeneration of bigtableadmin v2 client
  generated/google-apis-bigtableadmin_v2/CHANGELOG.md
  generated/google-apis-bigtableadmin_v2/OVERVIEW.md
  generated/google-apis-bigtableadmin_v2/synth.metadata
Labels: automerge

#7645 feat: Automated regeneration of billingbudgets v1beta1 client
  generated/google-apis-billingbudgets_v1beta1/CHANGELOG.md
  generated/google-apis-billingbudgets_v1beta1/OVERVIEW.md
  generated/google-apis-billingbudgets_v1beta1/lib/google/apis/billingbudgets_v1beta1/gem_version.rb
  generated/google-apis-billingbudgets_v1beta1/synth.metadata
Labels: automerge

#7632 feat: Automated regeneration of artifactregistry v1beta1 client
  generated/google-apis-artifactregistry_v1beta1/CHANGELOG.md
  generated/google-apis-artifactregistry_v1beta1/OVERVIEW.md
  generated/google-apis-artifactregistry_v1beta1/lib/google/apis/artifactregistry_v1beta1/gem_version.rb
  generated/google-apis-artifactregistry_v1beta1/synth.metadata
Labels: automerge

#7640 feat: Automated regeneration of bigqueryreservation v1 client
  generated/google-apis-bigqueryreservation_v1/CHANGELOG.md
  generated/google-apis-bigqueryreservation_v1/OVERVIEW.md
  generated/google-apis-bigqueryreservation_v1/lib/google/apis/bigqueryreservation_v1/gem_version.rb
  generated/google-apis-bigqueryreservation_v1/synth.metadata
Labels: automerge

#7646 feat: Automated regeneration of binaryauthorization v1 client
  generated/google-apis-binaryauthorization_v1/CHANGELOG.md
  generated/google-apis-binaryauthorization_v1/OVERVIEW.md
  generated/google-apis-binaryauthorization_v1/lib/google/apis/binaryauthorization_v1/gem_version.rb
  generated/google-apis-binaryauthorization_v1/synth.metadata
Labels: automerge

#7611 feat: Automated regeneration of admob v1beta client
  generated/google-apis-admob_v1beta/CHANGELOG.md
  generated/google-apis-admob_v1beta/OVERVIEW.md
  generated/google-apis-admob_v1beta/lib/google/apis/admob_v1beta/gem_version.rb
  generated/google-apis-admob_v1beta/synth.metadata
Labels: automerge

#7644 feat: Automated regeneration of billingbudgets v1 client
  generated/google-apis-billingbudgets_v1/CHANGELOG.md
  generated/google-apis-billingbudgets_v1/OVERVIEW.md
  generated/google-apis-billingbudgets_v1/lib/google/apis/billingbudgets_v1/gem_version.rb
  generated/google-apis-billingbudgets_v1/synth.metadata
Labels: automerge

#7650 feat: Automated regeneration of books v1 client
  generated/google-apis-books_v1/CHANGELOG.md
  generated/google-apis-books_v1/OVERVIEW.md
  generated/google-apis-books_v1/lib/google/apis/books_v1/gem_version.rb
  generated/google-apis-books_v1/synth.metadata
Labels: automerge

#7639 feat: Automated regeneration of bigquerydatatransfer v1 client
  generated/google-apis-bigquerydatatransfer_v1/CHANGELOG.md
  generated/google-apis-bigquerydatatransfer_v1/OVERVIEW.md
  generated/google-apis-bigquerydatatransfer_v1/lib/google/apis/bigquerydatatransfer_v1/gem_version.rb
  generated/google-apis-bigquerydatatransfer_v1/synth.metadata
Labels: automerge

#7649 feat: Automated regeneration of blogger v3 client
  generated/google-apis-blogger_v3/CHANGELOG.md
  generated/google-apis-blogger_v3/OVERVIEW.md
  generated/google-apis-blogger_v3/lib/google/apis/blogger_v3/gem_version.rb
  generated/google-apis-blogger_v3/synth.metadata
Labels: automerge

#7655 feat: Automated regeneration of chromeuxreport v1 client
  generated/google-apis-chromeuxreport_v1/CHANGELOG.md
  generated/google-apis-chromeuxreport_v1/OVERVIEW.md
  generated/google-apis-chromeuxreport_v1/lib/google/apis/chromeuxreport_v1/gem_version.rb
  generated/google-apis-chromeuxreport_v1/synth.metadata
Labels: automerge

#7656 feat: Automated regeneration of civicinfo v2 client
  generated/google-apis-civicinfo_v2/CHANGELOG.md
  generated/google-apis-civicinfo_v2/OVERVIEW.md
  generated/google-apis-civicinfo_v2/lib/google/apis/civicinfo_v2/gem_version.rb
  generated/google-apis-civicinfo_v2/synth.metadata
Labels: automerge

#7635 feat: Automated regeneration of authorizedbuyersmarketplace v1 client
  generated/google-apis-authorizedbuyersmarketplace_v1/CHANGELOG.md
  generated/google-apis-authorizedbuyersmarketplace_v1/OVERVIEW.md
  generated/google-apis-authorizedbuyersmarketplace_v1/lib/google/apis/authorizedbuyersmarketplace_v1/gem_version.rb
  generated/google-apis-authorizedbuyersmarketplace_v1/synth.metadata
Labels: automerge

#7638 feat: Automated regeneration of bigqueryconnection v1beta1 client
  generated/google-apis-bigqueryconnection_v1beta1/CHANGELOG.md
  generated/google-apis-bigqueryconnection_v1beta1/OVERVIEW.md
  generated/google-apis-bigqueryconnection_v1beta1/lib/google/apis/bigqueryconnection_v1beta1/gem_version.rb
  generated/google-apis-bigqueryconnection_v1beta1/synth.metadata
Labels: automerge

#7652 feat: Automated regeneration of chat v1 client
  generated/google-apis-chat_v1/CHANGELOG.md
  generated/google-apis-chat_v1/OVERVIEW.md
  generated/google-apis-chat_v1/lib/google/apis/chat_v1/gem_version.rb
  generated/google-apis-chat_v1/synth.metadata
Labels: automerge

#7654 feat: Automated regeneration of chromepolicy v1 client
  generated/google-apis-chromepolicy_v1/CHANGELOG.md
  generated/google-apis-chromepolicy_v1/OVERVIEW.md
  generated/google-apis-chromepolicy_v1/lib/google/apis/chromepolicy_v1/gem_version.rb
  generated/google-apis-chromepolicy_v1/synth.metadata
Labels: automerge

#7641 feat: Automated regeneration of bigqueryreservation v1beta1 client
  generated/google-apis-bigqueryreservation_v1beta1/CHANGELOG.md
  generated/google-apis-bigqueryreservation_v1beta1/OVERVIEW.md
  generated/google-apis-bigqueryreservation_v1beta1/lib/google/apis/bigqueryreservation_v1beta1/gem_version.rb
  generated/google-apis-bigqueryreservation_v1beta1/synth.metadata
Labels: automerge

#7653 feat: Automated regeneration of chromemanagement v1 client
  generated/google-apis-chromemanagement_v1/CHANGELOG.md
  generated/google-apis-chromemanagement_v1/OVERVIEW.md
  generated/google-apis-chromemanagement_v1/lib/google/apis/chromemanagement_v1/gem_version.rb
  generated/google-apis-chromemanagement_v1/synth.metadata
Labels: automerge

#7648 feat: Automated regeneration of blogger v2 client
  generated/google-apis-blogger_v2/CHANGELOG.md
  generated/google-apis-blogger_v2/OVERVIEW.md
  generated/google-apis-blogger_v2/lib/google/apis/blogger_v2/gem_version.rb
  generated/google-apis-blogger_v2/synth.metadata
Labels: automerge

#7658 feat: Automated regeneration of cloudasset v1 client
  generated/google-apis-cloudasset_v1/CHANGELOG.md
  generated/google-apis-cloudasset_v1/OVERVIEW.md
  generated/google-apis-cloudasset_v1/lib/google/apis/cloudasset_v1/gem_version.rb
  generated/google-apis-cloudasset_v1/synth.metadata
Labels: automerge

#7647 feat: Automated regeneration of binaryauthorization v1beta1 client
  generated/google-apis-binaryauthorization_v1beta1/CHANGELOG.md
  generated/google-apis-binaryauthorization_v1beta1/OVERVIEW.md
  generated/google-apis-binaryauthorization_v1beta1/lib/google/apis/binaryauthorization_v1beta1/gem_version.rb
  generated/google-apis-binaryauthorization_v1beta1/synth.metadata
Labels: automerge

#7659 feat: Automated regeneration of cloudasset v1beta1 client
  generated/google-apis-cloudasset_v1beta1/CHANGELOG.md
  generated/google-apis-cloudasset_v1beta1/OVERVIEW.md
  generated/google-apis-cloudasset_v1beta1/lib/google/apis/cloudasset_v1beta1/gem_version.rb
  generated/google-apis-cloudasset_v1beta1/synth.metadata
Labels: automerge

#7661 feat: Automated regeneration of cloudasset v1p4beta1 client
  generated/google-apis-cloudasset_v1p4beta1/CHANGELOG.md
  generated/google-apis-cloudasset_v1p4beta1/OVERVIEW.md
  generated/google-apis-cloudasset_v1p4beta1/lib/google/apis/cloudasset_v1p4beta1/gem_version.rb
  generated/google-apis-cloudasset_v1p4beta1/synth.metadata
Labels: automerge

#7651 feat: Automated regeneration of calendar v3 client
  generated/google-apis-calendar_v3/CHANGELOG.md
  generated/google-apis-calendar_v3/OVERVIEW.md
  generated/google-apis-calendar_v3/lib/google/apis/calendar_v3/gem_version.rb
  generated/google-apis-calendar_v3/synth.metadata
Labels: automerge

#7663 feat: Automated regeneration of cloudasset v1p7beta1 client
  generated/google-apis-cloudasset_v1p7beta1/CHANGELOG.md
  generated/google-apis-cloudasset_v1p7beta1/OVERVIEW.md
  generated/google-apis-cloudasset_v1p7beta1/lib/google/apis/cloudasset_v1p7beta1/gem_version.rb
  generated/google-apis-cloudasset_v1p7beta1/synth.metadata
Labels: automerge

#7664 feat: Automated regeneration of cloudbilling v1 client
  generated/google-apis-cloudbilling_v1/CHANGELOG.md
  generated/google-apis-cloudbilling_v1/OVERVIEW.md
  generated/google-apis-cloudbilling_v1/lib/google/apis/cloudbilling_v1/gem_version.rb
  generated/google-apis-cloudbilling_v1/lib/google/apis/cloudbilling_v1/service.rb
  generated/google-apis-cloudbilling_v1/synth.metadata
Labels: automerge

#7665 feat: Automated regeneration of cloudbuild v1 client
  generated/google-apis-cloudbuild_v1/CHANGELOG.md
  generated/google-apis-cloudbuild_v1/OVERVIEW.md
  generated/google-apis-cloudbuild_v1/lib/google/apis/cloudbuild_v1/gem_version.rb
  generated/google-apis-cloudbuild_v1/synth.metadata
Labels: automerge

#7662 feat: Automated regeneration of cloudasset v1p5beta1 client
  generated/google-apis-cloudasset_v1p5beta1/CHANGELOG.md
  generated/google-apis-cloudasset_v1p5beta1/OVERVIEW.md
  generated/google-apis-cloudasset_v1p5beta1/lib/google/apis/cloudasset_v1p5beta1/gem_version.rb
  generated/google-apis-cloudasset_v1p5beta1/synth.metadata
Labels: automerge

#7668 feat: Automated regeneration of cloudbuild v1beta1 client
  generated/google-apis-cloudbuild_v1beta1/CHANGELOG.md
  generated/google-apis-cloudbuild_v1beta1/OVERVIEW.md
  generated/google-apis-cloudbuild_v1beta1/lib/google/apis/cloudbuild_v1beta1/gem_version.rb
  generated/google-apis-cloudbuild_v1beta1/synth.metadata
Labels: automerge

#7666 feat: Automated regeneration of cloudbuild v1alpha1 client
  generated/google-apis-cloudbuild_v1alpha1/CHANGELOG.md
  generated/google-apis-cloudbuild_v1alpha1/OVERVIEW.md
  generated/google-apis-cloudbuild_v1alpha1/lib/google/apis/cloudbuild_v1alpha1/gem_version.rb
  generated/google-apis-cloudbuild_v1alpha1/synth.metadata
Labels: automerge

#7672 feat: Automated regeneration of clouderrorreporting v1beta1 client
  generated/google-apis-clouderrorreporting_v1beta1/CHANGELOG.md
  generated/google-apis-clouderrorreporting_v1beta1/OVERVIEW.md
  generated/google-apis-clouderrorreporting_v1beta1/lib/google/apis/clouderrorreporting_v1beta1/gem_version.rb
  generated/google-apis-clouderrorreporting_v1beta1/synth.metadata
Labels: automerge

#7673 feat: Automated regeneration of cloudfunctions v1 client
  generated/google-apis-cloudfunctions_v1/CHANGELOG.md
  generated/google-apis-cloudfunctions_v1/OVERVIEW.md
  generated/google-apis-cloudfunctions_v1/lib/google/apis/cloudfunctions_v1/gem_version.rb
  generated/google-apis-cloudfunctions_v1/synth.metadata
Labels: automerge

#7660 feat: Automated regeneration of cloudasset v1p1beta1 client
  generated/google-apis-cloudasset_v1p1beta1/CHANGELOG.md
  generated/google-apis-cloudasset_v1p1beta1/OVERVIEW.md
  generated/google-apis-cloudasset_v1p1beta1/lib/google/apis/cloudasset_v1p1beta1/gem_version.rb
  generated/google-apis-cloudasset_v1p1beta1/synth.metadata
Labels: automerge

#7671 feat: Automated regeneration of clouddeploy v1 client
  generated/google-apis-clouddeploy_v1/CHANGELOG.md
  generated/google-apis-clouddeploy_v1/OVERVIEW.md
  generated/google-apis-clouddeploy_v1/lib/google/apis/clouddeploy_v1/gem_version.rb
  generated/google-apis-clouddeploy_v1/synth.metadata
Labels: automerge

#7670 feat: Automated regeneration of clouddebugger v2 client
  generated/google-apis-clouddebugger_v2/CHANGELOG.md
  generated/google-apis-clouddebugger_v2/OVERVIEW.md
  generated/google-apis-clouddebugger_v2/lib/google/apis/clouddebugger_v2/gem_version.rb
  generated/google-apis-clouddebugger_v2/synth.metadata
Labels: automerge

#7669 feat: Automated regeneration of cloudchannel v1 client
  generated/google-apis-cloudchannel_v1/CHANGELOG.md
  generated/google-apis-cloudchannel_v1/OVERVIEW.md
  generated/google-apis-cloudchannel_v1/lib/google/apis/cloudchannel_v1/gem_version.rb
  generated/google-apis-cloudchannel_v1/synth.metadata
Labels: automerge

#7667 feat: Automated regeneration of cloudbuild v1alpha2 client
  generated/google-apis-cloudbuild_v1alpha2/CHANGELOG.md
  generated/google-apis-cloudbuild_v1alpha2/OVERVIEW.md
  generated/google-apis-cloudbuild_v1alpha2/lib/google/apis/cloudbuild_v1alpha2/gem_version.rb
  generated/google-apis-cloudbuild_v1alpha2/synth.metadata
Labels: automerge

#7657 feat: Automated regeneration of classroom v1 client
  generated/google-apis-classroom_v1/CHANGELOG.md
  generated/google-apis-classroom_v1/OVERVIEW.md
  generated/google-apis-classroom_v1/lib/google/apis/classroom_v1/gem_version.rb
  generated/google-apis-classroom_v1/synth.metadata
Labels: automerge

#7674 feat: Automated regeneration of datacatalog v1 client
  generated/google-apis-datacatalog_v1/CHANGELOG.md
  generated/google-apis-datacatalog_v1/OVERVIEW.md
  generated/google-apis-datacatalog_v1/lib/google/apis/datacatalog_v1/gem_version.rb
  generated/google-apis-datacatalog_v1/synth.metadata
Labels: automerge

#7675 feat: Automated regeneration of datacatalog v1beta1 client
  generated/google-apis-datacatalog_v1beta1/CHANGELOG.md
  generated/google-apis-datacatalog_v1beta1/OVERVIEW.md
  generated/google-apis-datacatalog_v1beta1/lib/google/apis/datacatalog_v1beta1/gem_version.rb
  generated/google-apis-datacatalog_v1beta1/synth.metadata
Labels: automerge

#7677 feat: Automated regeneration of datafusion v1 client
  generated/google-apis-datafusion_v1/CHANGELOG.md
  generated/google-apis-datafusion_v1/OVERVIEW.md
  generated/google-apis-datafusion_v1/lib/google/apis/datafusion_v1/gem_version.rb
  generated/google-apis-datafusion_v1/synth.metadata
Labels: automerge

#7679 feat: Automated regeneration of datalabeling v1beta1 client
  generated/google-apis-datalabeling_v1beta1/CHANGELOG.md
  generated/google-apis-datalabeling_v1beta1/OVERVIEW.md
  generated/google-apis-datalabeling_v1beta1/lib/google/apis/datalabeling_v1beta1/gem_version.rb
  generated/google-apis-datalabeling_v1beta1/synth.metadata
Labels: automerge

#7676 feat: Automated regeneration of dataflow v1b3 client
  generated/google-apis-dataflow_v1b3/CHANGELOG.md
  generated/google-apis-dataflow_v1b3/OVERVIEW.md
  generated/google-apis-dataflow_v1b3/lib/google/apis/dataflow_v1b3/gem_version.rb
  generated/google-apis-dataflow_v1b3/synth.metadata
Labels: automerge

#7680 feat: Automated regeneration of datamigration v1 client
  generated/google-apis-datamigration_v1/CHANGELOG.md
  generated/google-apis-datamigration_v1/OVERVIEW.md
  generated/google-apis-datamigration_v1/lib/google/apis/datamigration_v1/gem_version.rb
  generated/google-apis-datamigration_v1/synth.metadata
Labels: automerge

#7681 feat: Automated regeneration of datamigration v1beta1 client
  generated/google-apis-datamigration_v1beta1/CHANGELOG.md
  generated/google-apis-datamigration_v1beta1/OVERVIEW.md
  generated/google-apis-datamigration_v1beta1/lib/google/apis/datamigration_v1beta1/gem_version.rb
  generated/google-apis-datamigration_v1beta1/synth.metadata
Labels: automerge

#7684 feat: Automated regeneration of datastore v1 client
  generated/google-apis-datastore_v1/CHANGELOG.md
  generated/google-apis-datastore_v1/OVERVIEW.md
  generated/google-apis-datastore_v1/lib/google/apis/datastore_v1/gem_version.rb
  generated/google-apis-datastore_v1/synth.metadata
Labels: automerge

#7686 feat: Automated regeneration of datastore v1beta3 client
  generated/google-apis-datastore_v1beta3/CHANGELOG.md
  generated/google-apis-datastore_v1beta3/OVERVIEW.md
  generated/google-apis-datastore_v1beta3/lib/google/apis/datastore_v1beta3/gem_version.rb
  generated/google-apis-datastore_v1beta3/synth.metadata
Labels: automerge

#7678 feat: Automated regeneration of datafusion v1beta1 client
  generated/google-apis-datafusion_v1beta1/CHANGELOG.md
  generated/google-apis-datafusion_v1beta1/OVERVIEW.md
  generated/google-apis-datafusion_v1beta1/lib/google/apis/datafusion_v1beta1/gem_version.rb
  generated/google-apis-datafusion_v1beta1/synth.metadata
Labels: automerge

#7685 feat: Automated regeneration of datastore v1beta1 client
  generated/google-apis-datastore_v1beta1/CHANGELOG.md
  generated/google-apis-datastore_v1beta1/OVERVIEW.md
  generated/google-apis-datastore_v1beta1/lib/google/apis/datastore_v1beta1/gem_version.rb
  generated/google-apis-datastore_v1beta1/synth.metadata
Labels: automerge

#7688 feat: Automated regeneration of datastream v1alpha1 client
  generated/google-apis-datastream_v1alpha1/CHANGELOG.md
  generated/google-apis-datastream_v1alpha1/OVERVIEW.md
  generated/google-apis-datastream_v1alpha1/lib/google/apis/datastream_v1alpha1/gem_version.rb
  generated/google-apis-datastream_v1alpha1/synth.metadata
Labels: automerge

#7689 feat: Automated regeneration of deploymentmanager alpha client
  generated/google-apis-deploymentmanager_alpha/CHANGELOG.md
  generated/google-apis-deploymentmanager_alpha/OVERVIEW.md
  generated/google-apis-deploymentmanager_alpha/lib/google/apis/deploymentmanager_alpha/gem_version.rb
  generated/google-apis-deploymentmanager_alpha/synth.metadata
Labels: automerge

#7687 feat: Automated regeneration of datastream v1 client
  generated/google-apis-datastream_v1/CHANGELOG.md
  generated/google-apis-datastream_v1/OVERVIEW.md
  generated/google-apis-datastream_v1/lib/google/apis/datastream_v1/gem_version.rb
  generated/google-apis-datastream_v1/synth.metadata
Labels: automerge

#7691 feat: Automated regeneration of deploymentmanager v2beta client
  generated/google-apis-deploymentmanager_v2beta/CHANGELOG.md
  generated/google-apis-deploymentmanager_v2beta/OVERVIEW.md
  generated/google-apis-deploymentmanager_v2beta/lib/google/apis/deploymentmanager_v2beta/gem_version.rb
  generated/google-apis-deploymentmanager_v2beta/synth.metadata
Labels: automerge

#7683 feat: Automated regeneration of dataproc v1 client
  generated/google-apis-dataproc_v1/CHANGELOG.md
  generated/google-apis-dataproc_v1/OVERVIEW.md
  generated/google-apis-dataproc_v1/lib/google/apis/dataproc_v1/gem_version.rb
  generated/google-apis-dataproc_v1/synth.metadata
Labels: automerge

#7692 feat: Automated regeneration of dfareporting v3.3 client
  generated/google-apis-dfareporting_v3_3/CHANGELOG.md
  generated/google-apis-dfareporting_v3_3/OVERVIEW.md
  generated/google-apis-dfareporting_v3_3/lib/google/apis/dfareporting_v3_3/gem_version.rb
  generated/google-apis-dfareporting_v3_3/synth.metadata
Labels: automerge

#7682 feat: Automated regeneration of datapipelines v1 client
  generated/google-apis-datapipelines_v1/CHANGELOG.md
  generated/google-apis-datapipelines_v1/OVERVIEW.md
  generated/google-apis-datapipelines_v1/lib/google/apis/datapipelines_v1/gem_version.rb
  generated/google-apis-datapipelines_v1/synth.metadata
Labels: automerge

#7695 feat: Automated regeneration of dialogflow v2 client
  generated/google-apis-dialogflow_v2/CHANGELOG.md
  generated/google-apis-dialogflow_v2/OVERVIEW.md
  generated/google-apis-dialogflow_v2/lib/google/apis/dialogflow_v2/gem_version.rb
  generated/google-apis-dialogflow_v2/synth.metadata
Labels: automerge

#7694 feat: Automated regeneration of dfareporting v3.5 client
  generated/google-apis-dfareporting_v3_5/CHANGELOG.md
  generated/google-apis-dfareporting_v3_5/OVERVIEW.md
  generated/google-apis-dfareporting_v3_5/lib/google/apis/dfareporting_v3_5/gem_version.rb
  generated/google-apis-dfareporting_v3_5/synth.metadata
Labels: automerge

#7696 feat: Automated regeneration of dialogflow v2beta1 client
  generated/google-apis-dialogflow_v2beta1/CHANGELOG.md
  generated/google-apis-dialogflow_v2beta1/OVERVIEW.md
  generated/google-apis-dialogflow_v2beta1/lib/google/apis/dialogflow_v2beta1/gem_version.rb
  generated/google-apis-dialogflow_v2beta1/synth.metadata
Labels: automerge

#7693 feat: Automated regeneration of dfareporting v3.4 client
  generated/google-apis-dfareporting_v3_4/CHANGELOG.md
  generated/google-apis-dfareporting_v3_4/OVERVIEW.md
  generated/google-apis-dfareporting_v3_4/lib/google/apis/dfareporting_v3_4/gem_version.rb
  generated/google-apis-dfareporting_v3_4/synth.metadata
Labels: automerge

#7698 feat: Automated regeneration of dialogflow v3beta1 client
  generated/google-apis-dialogflow_v3beta1/CHANGELOG.md
  generated/google-apis-dialogflow_v3beta1/OVERVIEW.md
  generated/google-apis-dialogflow_v3beta1/lib/google/apis/dialogflow_v3beta1/gem_version.rb
  generated/google-apis-dialogflow_v3beta1/synth.metadata
Labels: automerge

#7697 feat: Automated regeneration of dialogflow v3 client
  generated/google-apis-dialogflow_v3/CHANGELOG.md
  generated/google-apis-dialogflow_v3/OVERVIEW.md
  generated/google-apis-dialogflow_v3/lib/google/apis/dialogflow_v3/gem_version.rb
  generated/google-apis-dialogflow_v3/synth.metadata
Labels: automerge

#7701 feat: Automated regeneration of displayvideo v1 client
  generated/google-apis-displayvideo_v1/CHANGELOG.md
  generated/google-apis-displayvideo_v1/OVERVIEW.md
  generated/google-apis-displayvideo_v1/lib/google/apis/displayvideo_v1/gem_version.rb
  generated/google-apis-displayvideo_v1/synth.metadata
Labels: automerge

#7699 feat: Automated regeneration of digitalassetlinks v1 client
  generated/google-apis-digitalassetlinks_v1/CHANGELOG.md
  generated/google-apis-digitalassetlinks_v1/OVERVIEW.md
  generated/google-apis-digitalassetlinks_v1/lib/google/apis/digitalassetlinks_v1/gem_version.rb
  generated/google-apis-digitalassetlinks_v1/synth.metadata
Labels: automerge

#7704 feat: Automated regeneration of dns v1beta2 client
  generated/google-apis-dns_v1beta2/CHANGELOG.md
  generated/google-apis-dns_v1beta2/OVERVIEW.md
  generated/google-apis-dns_v1beta2/lib/google/apis/dns_v1beta2/gem_version.rb
  generated/google-apis-dns_v1beta2/synth.metadata
Labels: automerge

#7706 feat: Automated regeneration of documentai v1 client
  generated/google-apis-documentai_v1/CHANGELOG.md
  generated/google-apis-documentai_v1/OVERVIEW.md
  generated/google-apis-documentai_v1/lib/google/apis/documentai_v1/gem_version.rb
  generated/google-apis-documentai_v1/synth.metadata
Labels: automerge

#7700 feat: Automated regeneration of discovery v1 client
  generated/google-apis-discovery_v1/CHANGELOG.md
  generated/google-apis-discovery_v1/OVERVIEW.md
  generated/google-apis-discovery_v1/lib/google/apis/discovery_v1/gem_version.rb
  generated/google-apis-discovery_v1/synth.metadata
Labels: automerge

#7707 feat: Automated regeneration of documentai v1beta2 client
  generated/google-apis-documentai_v1beta2/CHANGELOG.md
  generated/google-apis-documentai_v1beta2/OVERVIEW.md
  generated/google-apis-documentai_v1beta2/lib/google/apis/documentai_v1beta2/gem_version.rb
  generated/google-apis-documentai_v1beta2/synth.metadata
Labels: automerge

#7705 feat: Automated regeneration of docs v1 client
  generated/google-apis-docs_v1/CHANGELOG.md
  generated/google-apis-docs_v1/OVERVIEW.md
  generated/google-apis-docs_v1/lib/google/apis/docs_v1/gem_version.rb
  generated/google-apis-docs_v1/synth.metadata
Labels: automerge

#7711 feat: Automated regeneration of domains v1beta1 client
  generated/google-apis-domains_v1beta1/CHANGELOG.md
  generated/google-apis-domains_v1beta1/OVERVIEW.md
  generated/google-apis-domains_v1beta1/lib/google/apis/domains_v1beta1/gem_version.rb
  generated/google-apis-domains_v1beta1/synth.metadata
Labels: automerge

#7712 feat: Automated regeneration of domainsrdap v1 client
  generated/google-apis-domainsrdap_v1/CHANGELOG.md
  generated/google-apis-domainsrdap_v1/OVERVIEW.md
  generated/google-apis-domainsrdap_v1/lib/google/apis/domainsrdap_v1/gem_version.rb
  generated/google-apis-domainsrdap_v1/synth.metadata
Labels: automerge

#7708 feat: Automated regeneration of documentai v1beta3 client
  generated/google-apis-documentai_v1beta3/CHANGELOG.md
  generated/google-apis-documentai_v1beta3/OVERVIEW.md
  generated/google-apis-documentai_v1beta3/lib/google/apis/documentai_v1beta3/gem_version.rb
  generated/google-apis-documentai_v1beta3/synth.metadata
Labels: automerge

#7703 feat: Automated regeneration of dns v1 client
  generated/google-apis-dns_v1/CHANGELOG.md
  generated/google-apis-dns_v1/OVERVIEW.md
  generated/google-apis-dns_v1/lib/google/apis/dns_v1/gem_version.rb
  generated/google-apis-dns_v1/synth.metadata
Labels: automerge

#7710 feat: Automated regeneration of domains v1alpha2 client
  generated/google-apis-domains_v1alpha2/CHANGELOG.md
  generated/google-apis-domains_v1alpha2/OVERVIEW.md
  generated/google-apis-domains_v1alpha2/lib/google/apis/domains_v1alpha2/gem_version.rb
  generated/google-apis-domains_v1alpha2/synth.metadata
Labels: automerge

#7715 feat: Automated regeneration of drive v2 client
  generated/google-apis-drive_v2/CHANGELOG.md
  generated/google-apis-drive_v2/OVERVIEW.md
  generated/google-apis-drive_v2/lib/google/apis/drive_v2/gem_version.rb
  generated/google-apis-drive_v2/synth.metadata
Labels: automerge

#7709 feat: Automated regeneration of domains v1 client
  generated/google-apis-domains_v1/CHANGELOG.md
  generated/google-apis-domains_v1/OVERVIEW.md
  generated/google-apis-domains_v1/lib/google/apis/domains_v1/gem_version.rb
  generated/google-apis-domains_v1/synth.metadata
Labels: automerge

#7716 feat: Automated regeneration of drive v3 client
  generated/google-apis-drive_v3/CHANGELOG.md
  generated/google-apis-drive_v3/OVERVIEW.md
  generated/google-apis-drive_v3/lib/google/apis/drive_v3/gem_version.rb
  generated/google-apis-drive_v3/synth.metadata
Labels: automerge

#7702 feat: Automated regeneration of dlp v2 client
  generated/google-apis-dlp_v2/CHANGELOG.md
  generated/google-apis-dlp_v2/OVERVIEW.md
  generated/google-apis-dlp_v2/lib/google/apis/dlp_v2/gem_version.rb
  generated/google-apis-dlp_v2/synth.metadata
Labels: automerge

#7717 feat: Automated regeneration of driveactivity v2 client
  generated/google-apis-driveactivity_v2/CHANGELOG.md
  generated/google-apis-driveactivity_v2/OVERVIEW.md
  generated/google-apis-driveactivity_v2/lib/google/apis/driveactivity_v2/gem_version.rb
  generated/google-apis-driveactivity_v2/synth.metadata
Labels: automerge
